export QEMU_LD_PREFIX:=/usr/mips64-linux-gnuabi64/
ACEUNIT_HOME:=../../../
vpath %.c $(ACEUNIT_HOME)lib/
include $(ACEUNIT_HOME)/lib/Makefile
CC=mips64-linux-gnuabi64-gcc-10
AR=mips64-linux-gnuabi64-gcc-ar-10
