export QEMU_LD_PREFIX:=/usr/powerpc64le-linux-gnu/
ACEUNIT_HOME:=../../../
vpath %.c $(ACEUNIT_HOME)lib/
include $(ACEUNIT_HOME)/lib/Makefile
CC=powerpc64le-linux-gnu-gcc-12
AR=powerpc64le-linux-gnu-gcc-ar-12
