/** Use return to exit a test case with a failed assertion. */
#define ACEUNIT_ASSERTION_STYLE ACEUNIT_ASSERTION_STYLE_RETURN

#define ACEUNIT_EXPLICIT_MESSAGES
#define ACEUNIT_EXPLICIT_MESSAGES_INLINE_BUFFER
#define ACEUNIT_EXPLICIT_MSG_BUF_SIZE 512
